### ISSUE TITLE
download data- no genome

### ISSUE THREAD

**Issue by fifdick** [charite/asdpex#12]
I followed the instructions on the README. 
I executed downloadData.sh, which threw no error.  All subsequent steps were also successful until I wanted to start alignment. The index file for the genome was missing. I failed to index it  with samtools. After checking the file (the genome), I saw it was empty.
I checked the script downloadData.sh for the genome download link and found this:

`url38="ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_full_analysis_set.fna.gz"`

Trying to execute:
` wget --progress=bar -O test.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_full_analysis_set.fna.gz
`
Gave me error:

> No such directory ‘genomes/all/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids’.

After checking the ftp page I found this to be the correct link, with which the download of the genome worked and subsequently also the indexing with samtools and the rest of the following steps.

> ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/

**Comment by GodloveD** [comment]
I also ran into this error.  It would be nice to see the download script updated.

**Comment by martenj** [comment]
Hi, 
sorry for this (huge) delay. The download scripts should be fixed now in release 0.3.

Best.
